{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.library\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSCoding","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSExtensionRequestHandling","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSObject","doc:\/\/ch.ti8m.idcheck.library\/s7CVarArgP","doc:\/\/ch.ti8m.idcheck.library\/s28CustomDebugStringConvertibleP","doc:\/\/ch.ti8m.idcheck.library\/s23CustomStringConvertibleP","doc:\/\/ch.ti8m.idcheck.library\/SQ","doc:\/\/ch.ti8m.idcheck.library\/SH","doc:\/\/ch.ti8m.idcheck.library\/s8SendableP","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIAppearanceContainer","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIContentContainer","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIFocusEnvironment","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIResponderStandardEditActions","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIStateRestoring","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UITraitEnvironment","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This view controller verifies the selfies, it communicates with the integrating application through it’s delegate protocol"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"}],"title":"IDCheckSelfieVerificationLegacyViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@IDCheckLib@objc(cs)IDCheckSelfieVerificationLegacyViewController","modules":[{"name":"IDCheckLib"}],"navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/init(config:processID:requiredHeadPoses:cameraSettings:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/cameraSettings","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/config","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/delegate","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/processID","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/requiredHeadPoses"]},{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/startRunning()","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/stopRunning(didFinish:)","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/viewDidAppear(_:)","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/viewDidLoad()"]}],"references":{"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationLegacyViewController/processID":{"role":"symbol","title":"processID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"processID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/processID","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller\/processid"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationLegacyViewController/stopRunning(didFinish:)":{"role":"symbol","title":"stopRunning(didFinish:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopRunning"},{"kind":"text","text":"("},{"kind":"externalParam","text":"didFinish"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/stopRunning(didFinish:)","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller\/stoprunning(didfinish:)"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationLegacyViewController":{"role":"symbol","title":"IDCheckSelfieVerificationLegacyViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"}],"abstract":[{"type":"text","text":"This view controller verifies the selfies, it communicates with the integrating application through it’s delegate protocol"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller"},"doc://ch.ti8m.idcheck.library/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/ch.ti8m.idcheck.library\/s8SendableP"},"doc://ch.ti8m.idcheck.library/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(cs)UIViewController"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationLegacyViewController/startRunning()":{"role":"symbol","title":"startRunning()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRunning"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/startRunning()","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller\/startrunning()"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationLegacyViewController/config":{"role":"symbol","title":"config","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckConfig","preciseIdentifier":"s:10IDCheckLib0A6ConfigV"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/config","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller\/config"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationLegacyViewController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller\/viewdidappear(_:)"},"doc://ch.ti8m.idcheck.library/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.library\/s28CustomDebugStringConvertibleP"},"doc://ch.ti8m.idcheck.library/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIAppearanceContainer"},"doc://ch.ti8m.idcheck.library/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://ch.ti8m.idcheck.library/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.library\/s23CustomStringConvertibleP"},"doc://ch.ti8m.idcheck.library/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIPasteConfigurationSupporting"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationLegacyViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckSelfieVerificationLegacyViewControllerDelegate","preciseIdentifier":"s:10IDCheckLib0A46SelfieVerificationLegacyViewControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller\/delegate"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationLegacyViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller\/viewdidload()"},"doc://ch.ti8m.idcheck.library/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIStateRestoring"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationLegacyViewController/requiredHeadPoses":{"role":"symbol","title":"requiredHeadPoses","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredHeadPoses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"IDCheckHeadPose","preciseIdentifier":"s:10IDCheckLib0A8HeadPoseO"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/requiredHeadPoses","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller\/requiredheadposes"},"doc://ch.ti8m.idcheck.library/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSObject"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib":{"role":"collection","title":"IDCheckLib","abstract":[{"type":"text","text":"IDCheckLib - document verification"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib"},"doc://ch.ti8m.idcheck.library/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIResponderStandardEditActions"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationLegacyViewController/cameraSettings":{"role":"symbol","title":"cameraSettings","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckSelfieVerificationCameraSettings","preciseIdentifier":"s:10IDCheckLib0A32SelfieVerificationCameraSettingsC"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/cameraSettings","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller\/camerasettings"},"doc://ch.ti8m.idcheck.library/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ch.ti8m.idcheck.library\/SQ"},"doc://ch.ti8m.idcheck.library/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSCoding"},"doc://ch.ti8m.idcheck.library/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ch.ti8m.idcheck.library\/SH"},"doc://ch.ti8m.idcheck.library/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UITraitEnvironment"},"doc://ch.ti8m.idcheck.library/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIFocusEnvironment"},"doc://ch.ti8m.idcheck.library/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIContentContainer"},"doc://ch.ti8m.idcheck.library/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSExtensionRequestHandling"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationLegacyViewController/init(config:processID:requiredHeadPoses:cameraSettings:)":{"role":"symbol","title":"init(config:processID:requiredHeadPoses:cameraSettings:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckConfig","preciseIdentifier":"s:10IDCheckLib0A6ConfigV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"processID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requiredHeadPoses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"IDCheckHeadPose","preciseIdentifier":"s:10IDCheckLib0A8HeadPoseO"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"cameraSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckSelfieVerificationCameraSettings","preciseIdentifier":"s:10IDCheckLib0A32SelfieVerificationCameraSettingsC"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes the IDCheckSelfieVerificationViewController with the required parameters"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/init(config:processID:requiredHeadPoses:cameraSettings:)","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller\/init(config:processid:requiredheadposes:camerasettings:)"},"doc://ch.ti8m.idcheck.library/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/ch.ti8m.idcheck.library\/s7CVarArgP"},"doc://ch.ti8m.idcheck.library/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIUserActivityRestoring"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"IDCheckSelfieVerificationLegacyViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/viewDidAppear(_:)","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.library\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationLegacyViewController\/title","value":"IDCheckSelfieVerificationLegacyViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationLegacyViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationLegacyViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationLegacyViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationLegacyViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationLegacyViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}