{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckEMRTDReader"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idchecklib\/idcheckemrtdreader"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idchecklib\/idcheckemrtdreader"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.library\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/ch.ti8m.idcheck.library\/7CoreNFC27NFCTagReaderSessionDelegateP","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSObject","doc:\/\/ch.ti8m.idcheck.library\/s7CVarArgP","doc:\/\/ch.ti8m.idcheck.library\/s28CustomDebugStringConvertibleP","doc:\/\/ch.ti8m.idcheck.library\/s23CustomStringConvertibleP","doc:\/\/ch.ti8m.idcheck.library\/SQ","doc:\/\/ch.ti8m.idcheck.library\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/init(config:chipAccessControlType:document:processID:taskID:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/chipAccessControlType","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/config","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/delegate","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/document","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/processID","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/taskID"]},{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/startReading()"]},{"title":"Type Properties","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/isAvailable"]},{"title":"Default Implementations","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/NFCTagReaderSessionDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckEMRTDReader"}],"title":"IDCheckEMRTDReader","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@IDCheckLib@objc(cs)IDCheckEMRTDReader","modules":[{"name":"IDCheckLib"}],"navigatorTitle":[{"kind":"identifier","text":"IDCheckEMRTDReader"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib"]]},"references":{"doc://ch.ti8m.idcheck.library/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ch.ti8m.idcheck.library\/SQ"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib":{"role":"collection","title":"IDCheckLib","abstract":[{"type":"text","text":"IDCheckLib - document verification"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib"},"doc://ch.ti8m.idcheck.library/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.library\/s23CustomStringConvertibleP"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDReader/taskID":{"role":"symbol","title":"taskID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"taskID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/taskID","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckemrtdreader\/taskid"},"doc://ch.ti8m.idcheck.library/7CoreNFC27NFCTagReaderSessionDelegateP":{"type":"unresolvable","title":"CoreNFC.NFCTagReaderSessionDelegate","identifier":"doc:\/\/ch.ti8m.idcheck.library\/7CoreNFC27NFCTagReaderSessionDelegateP"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDReader/document":{"role":"symbol","title":"document","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckEMRTDDocumentData","preciseIdentifier":"s:10IDCheckLib0A17EMRTDDocumentDataV"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/document","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckemrtdreader\/document"},"doc://ch.ti8m.idcheck.library/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ch.ti8m.idcheck.library\/SH"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDReader/config":{"role":"symbol","title":"config","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckConfig","preciseIdentifier":"s:10IDCheckLib0A6ConfigV"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/config","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckemrtdreader\/config"},"doc://ch.ti8m.idcheck.library/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(cs)NSObject"},"doc://ch.ti8m.idcheck.library/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/ch.ti8m.idcheck.library\/s7CVarArgP"},"doc://ch.ti8m.idcheck.library/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.library\/s28CustomDebugStringConvertibleP"},"doc://ch.ti8m.idcheck.library/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSObject"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDReader/isAvailable":{"role":"symbol","title":"isAvailable","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAvailable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/isAvailable","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckemrtdreader\/isavailable"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDReader/startReading()":{"role":"symbol","title":"startReading()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startReading"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/startReading()","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckemrtdreader\/startreading()"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDReader/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckEMRTDReaderDelegate","preciseIdentifier":"s:10IDCheckLib0A19EMRTDReaderDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckemrtdreader\/delegate"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDReader/NFCTagReaderSessionDelegate-Implementations":{"role":"collectionGroup","title":"NFCTagReaderSessionDelegate Implementations","abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/NFCTagReaderSessionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/idchecklib\/idcheckemrtdreader\/nfctagreadersessiondelegate-implementations"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDReader/init(config:chipAccessControlType:document:processID:taskID:)":{"role":"symbol","title":"init(config:chipAccessControlType:document:processID:taskID:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckConfig","preciseIdentifier":"s:10IDCheckLib0A6ConfigV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"chipAccessControlType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckChipAccessControlType","preciseIdentifier":"s:10IDCheckLib0A21ChipAccessControlTypeO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckEMRTDDocumentData","preciseIdentifier":"s:10IDCheckLib0A17EMRTDDocumentDataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"processID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"taskID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/init(config:chipAccessControlType:document:processID:taskID:)","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckemrtdreader\/init(config:chipaccesscontroltype:document:processid:taskid:)"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDReader":{"role":"symbol","title":"IDCheckEMRTDReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckEMRTDReader"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckEMRTDReader"}],"url":"\/documentation\/idchecklib\/idcheckemrtdreader"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDReader/chipAccessControlType":{"role":"symbol","title":"chipAccessControlType","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"chipAccessControlType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckChipAccessControlType","preciseIdentifier":"s:10IDCheckLib0A21ChipAccessControlTypeO"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/chipAccessControlType","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckemrtdreader\/chipaccesscontroltype"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDReader/processID":{"role":"symbol","title":"processID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"processID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader\/processID","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckemrtdreader\/processid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"IDCheckEMRTDReader"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IDCheckEMRTDReader"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IDCheckEMRTDReader"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.library\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckEMRTDReader"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckEMRTDReader\/title","value":"IDCheckEMRTDReader"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckEMRTDReader\/fragments","value":[{"kind":"identifier","text":"IDCheckEMRTDReader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}