{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationViewController"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"Migration-from-previous-versions","level":2,"type":"heading","text":"Migration from previous versions"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"requiredHeadPoses"}]}]},{"type":"text","text":" of type "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"IDCheckHeadPose"}]}]},{"type":"text","text":" was introduced in version 3.6.0, an example initialization may look like this:"}]},{"type":"codeListing","syntax":"swift","code":["\/\/ 3.6.0+","let selfieVerificationVC = IDCheckSelfieVerificationViewController(","    config: cfg,","    processID: self.delegate?.configuration?.processID ?? \"\",","    requiredHeadPoses: [IDCheckHeadPose.centerCenter],","    cameraSettings: IDCheckSelfieVerificationCameraSettings(","        orientation: .portrait,","        resolution: .hd","    )",")"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"However, usually the head poses come from the task. The view controller needs to be aware of them because it needs to know when it gathers all the required poses that are necessary. To get the required poses from the task do the following:"}]},{"type":"codeListing","syntax":"swift","code":["\/\/ 3.6.0+","IDCheckProcessAPIInstance.getSelfieVerificationData { [weak self] task in","    guard let requiredHeadPoses = task?.requiredHeadPoses else {","        return","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Just save it somewhere and then init the "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"IDCheckSelfieVerificationViewController"}]}]},{"type":"text","text":" as you normally would."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idchecklib\/idcheckselfieverificationviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idchecklib\/idcheckselfieverificationviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.library\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSCoding","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSExtensionRequestHandling","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSObject","doc:\/\/ch.ti8m.idcheck.library\/s7CVarArgP","doc:\/\/ch.ti8m.idcheck.library\/s28CustomDebugStringConvertibleP","doc:\/\/ch.ti8m.idcheck.library\/s23CustomStringConvertibleP","doc:\/\/ch.ti8m.idcheck.library\/SQ","doc:\/\/ch.ti8m.idcheck.library\/SH","doc:\/\/ch.ti8m.idcheck.library\/s8SendableP","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIAppearanceContainer","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIContentContainer","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIFocusEnvironment","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIResponderStandardEditActions","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIStateRestoring","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UITraitEnvironment","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController\/init(config:processID:taskID:delegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController\/config","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController\/delegate","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController\/processID","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController\/taskID"]},{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationViewController"}],"title":"IDCheckSelfieVerificationViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@IDCheckLib@objc(cs)IDCheckSelfieVerificationViewController","modules":[{"name":"IDCheckLib"}],"navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationViewController"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib"]]},"references":{"doc://ch.ti8m.idcheck.library/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIContentContainer"},"doc://ch.ti8m.idcheck.library/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://ch.ti8m.idcheck.library/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ch.ti8m.idcheck.library\/SQ"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib":{"role":"collection","title":"IDCheckLib","abstract":[{"type":"text","text":"IDCheckLib - document verification"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib"},"doc://ch.ti8m.idcheck.library/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIFocusEnvironment"},"doc://ch.ti8m.idcheck.library/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIUserActivityRestoring"},"doc://ch.ti8m.idcheck.library/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSExtensionRequestHandling"},"doc://ch.ti8m.idcheck.library/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIStateRestoring"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckSelfieVerificationViewControllerDelegate","preciseIdentifier":"s:10IDCheckLib0A40SelfieVerificationViewControllerDelegateP"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckselfieverificationviewcontroller\/delegate"},"doc://ch.ti8m.idcheck.library/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSObject"},"doc://ch.ti8m.idcheck.library/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSCoding"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationViewController/processID":{"role":"symbol","title":"processID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"processID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController\/processID","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckselfieverificationviewcontroller\/processid"},"doc://ch.ti8m.idcheck.library/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIResponderStandardEditActions"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationViewController/init(config:processID:taskID:delegate:)":{"role":"symbol","title":"init(config:processID:taskID:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckConfig","preciseIdentifier":"s:10IDCheckLib0A6ConfigV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"processID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"taskID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckSelfieVerificationViewControllerDelegate","preciseIdentifier":"s:10IDCheckLib0A40SelfieVerificationViewControllerDelegateP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController\/init(config:processID:taskID:delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckselfieverificationviewcontroller\/init(config:processid:taskid:delegate:)"},"doc://ch.ti8m.idcheck.library/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.library\/s23CustomStringConvertibleP"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationViewController/config":{"role":"symbol","title":"config","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckConfig","preciseIdentifier":"s:10IDCheckLib0A6ConfigV"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController\/config","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckselfieverificationviewcontroller\/config"},"doc://ch.ti8m.idcheck.library/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIPasteConfigurationSupporting"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationViewController":{"role":"symbol","title":"IDCheckSelfieVerificationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationViewController"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationviewcontroller"},"doc://ch.ti8m.idcheck.library/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(cs)UIViewController"},"doc://ch.ti8m.idcheck.library/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/ch.ti8m.idcheck.library\/s8SendableP"},"doc://ch.ti8m.idcheck.library/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.library\/s28CustomDebugStringConvertibleP"},"doc://ch.ti8m.idcheck.library/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ch.ti8m.idcheck.library\/SH"},"doc://ch.ti8m.idcheck.library/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/ch.ti8m.idcheck.library\/s7CVarArgP"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationviewcontroller\/viewdidload()"},"doc://ch.ti8m.idcheck.library/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UITraitEnvironment"},"doc://ch.ti8m.idcheck.library/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIAppearanceContainer"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationViewController/taskID":{"role":"symbol","title":"taskID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"taskID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController\/taskID","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckselfieverificationviewcontroller\/taskid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"IDCheckSelfieVerificationViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IDCheckSelfieVerificationViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IDCheckSelfieVerificationViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.library\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationViewController\/title","value":"IDCheckSelfieVerificationViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckSelfieVerificationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}