{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This article explains the steps needed when updating the library versions. For simple changes like renaming, the library uses the "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"obsoleted"}]}]},{"type":"text","text":" attribute where applicable, so that the compiler will mark the old call sites as errors and suggest the renaming. For more complex cases like additional parameters, removed parameters, and changes in the code structure that cannot be done through obsoleted, please check the specific topics below."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"At the time of writing the current version of the library is "},{"type":"strong","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/Version"}]}]}],"type":"aside","name":"Note"},{"anchor":"35x-to-360","level":2,"type":"heading","text":"3.5.x to 3.6.0"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewController"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedArea"},{"type":"text","text":" replaced the previously used "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Rectangle"}]}]},{"type":"text","text":" struct"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckScanMode"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationCameraSettings"}]}]}]},{"anchor":"381-to-382","level":2,"type":"heading","text":"3.8.1 to 3.8.2"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(Optional) "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewControllerDelegate\/documentVerificationRequire(_:lastScan:)-6xviq"},{"type":"text","text":" improves the previous version of this method which didn’t pass the "},{"type":"emphasis","inlineContent":[{"type":"text","text":"lastScan"}]},{"type":"text","text":" parameter. This gives the clients the ability to catch cases where the scanned document part keeps differing with what the library requires. For example when the library requires user to scan the back of the ID and the user keeps scanning the front, the integrating app could detect this and dispay a message to the user. The default implementation of this method is provided by the library and it does nothing, so the clients can treat this method as optional. If the client implements both this new method and the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewControllerDelegate\/documentVerificationRequire(_:)-9i4fd"},{"type":"text","text":" then this new method is called first."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(Optional) "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationPage"},{"type":"text","text":" added a new enum case "},{"type":"codeVoice","code":"supplementary"},{"type":"text","text":" which is used for some older IDs and permits in the paper form."}]}]}]},{"anchor":"38x-to-400","level":2,"type":"heading","text":"3.8.x to 4.0.0"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added method "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckLoggerProtocol\/warn(_:)"},{"type":"text","text":" to the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckLoggerProtocol"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Renamed IDCheckClientProcessAPI to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Introduced the following APIs for grouping the functionality that was previously all belonged in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI"},{"type":"text","text":":"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckAddressVerificationAPI"},{"type":"text","text":" as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI\/addressVerificationAPI"},{"type":"text","text":" property on "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentCorrectionAPI"},{"type":"text","text":" as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI\/documentCorrectionAPI"},{"type":"text","text":" property on "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationAPI"},{"type":"text","text":" as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI\/documentVerificationAPI"},{"type":"text","text":" property on "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDVerificationAPI"},{"type":"text","text":" as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI\/emrtdVerificationAPI"},{"type":"text","text":" property on "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationAPI"},{"type":"text","text":" as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI\/selfieVerificationAPI"},{"type":"text","text":" property on "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI"}]}]}]}]}]},{"anchor":"400-to-410","level":2,"type":"heading","text":"4.0.0 to 4.1.0"},{"type":"paragraph","inlineContent":[{"type":"text","text":"There were no changes to the public interfaces in this release, it was a bug-fix release."}]},{"anchor":"410-to-420","level":2,"type":"heading","text":"4.1.0 to 4.2.0"},{"type":"paragraph","inlineContent":[{"type":"text","text":"There were no changes to the public interfaces in this release, it was a compatibility release for Xcode 14 and iOS 16."}]},{"anchor":"420-to-421","level":2,"type":"heading","text":"4.2.0 to 4.2.1"},{"type":"paragraph","inlineContent":[{"type":"text","text":"There were no changes to the public interfaces in this release, it was a stability release that removed some redundant dependencies."}]},{"anchor":"421-to-500","level":2,"type":"heading","text":"4.2.1 to 5.0.0"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewControllerDelegate"},{"type":"text","text":" was refactored to closer reflect the native APIs where the controller is always passed to the delegate for providing necessary context. Check the protocol documentation for the migration steps."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewControllerInsufficiencyDelegate"},{"type":"text","text":" was refactored to closer reflect the native APIs where the controller is always passed to the delegate for providing necessary context. Check the protocol documentation for the migration steps."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The functionality to abort a task was added to the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI"},{"type":"text","text":". New method is called "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI\/abort(taskID:completionHandler:)"},{"type":"text","text":". After a task is aborted, it will have the new "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskState\/aborted"},{"type":"text","text":" state."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI"},{"type":"text","text":" initializer was updated to optionally take the certificatesInfo parameter: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI\/init(config:processID:certificatesInfo:)"}]}]}]},{"anchor":"500-to-501","level":2,"type":"heading","text":"5.0.0 to 5.0.1"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New property "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckNextTask\/taskPreviousInformation"},{"type":"text","text":" was added. You can inspect that object to detect when the previous task failed."}]},{"anchor":"501-to-502","level":2,"type":"heading","text":"5.0.1 to 5.0.2"},{"type":"paragraph","inlineContent":[{"type":"text","text":"There were no changes to the public interfaces in this release, it included only internal changes."}]},{"anchor":"502-to-503","level":2,"type":"heading","text":"5.0.2 to 5.0.3"},{"type":"paragraph","inlineContent":[{"type":"text","text":"We made the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskDocumentVerify\/images"},{"type":"text","text":" optional on the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskDocumentVerify"},{"type":"text","text":"."}]},{"anchor":"503-to-504","level":2,"type":"heading","text":"5.0.3 to 5.0.4"},{"type":"paragraph","inlineContent":[{"type":"text","text":"We made the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskLivenessVerify\/images"},{"type":"text","text":" and the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskLivenessVerify\/requiredHeadPoses"},{"type":"text","text":" optional on the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskLivenessVerify"},{"type":"text","text":"."}]},{"anchor":"504-to-602","level":2,"type":"heading","text":"5.0.4 to 6.0.2"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController"},{"type":"text","text":" and the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewControllerDelegate"},{"type":"text","text":" were renamed to the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController"},{"type":"text","text":" and the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewControllerDelegate"},{"type":"text","text":" respectively. These legacy objects can still be used if your tenant is configured to serve the legacy liveness from before the FaceTec liveness was introduced. The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController"},{"type":"text","text":" and the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewControllerDelegate"},{"type":"text","text":" names are now used for objects that support the new liveness."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"To use the new liveness, your tenant needs to be configured, please contact us if you want to update your config."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If your tenant is cofigured for the new liveness, you will need to use the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController"},{"type":"text","text":" (this name now belongs to the new liveness controller) and implement the methods in the new "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewControllerDelegate"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"themeBundle: Bundle?"},{"type":"text","text":" static property was added to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI"},{"type":"text","text":". You "},{"type":"strong","inlineContent":[{"type":"text","text":"must"}]},{"type":"text","text":" assign it before using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI"},{"type":"text","text":". The bundle you assign here should have the "},{"type":"codeVoice","code":"Localizable.string"},{"type":"text","text":" file in it with the translations for the new liveness component. "},{"type":"strong","inlineContent":[{"type":"text","text":"This was refactored in version 6.1.0, please refer to the migration steps for 6.1.0 to see how the theme should be set."}]}]}]}]},{"anchor":"602-to-610","level":2,"type":"heading","text":"6.0.2 to 6.1.0"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI\/theme"},{"type":"text","text":" changed type to "},{"type":"codeVoice","code":"IDCheckUITheme.IDCheckStyleProtocol"},{"type":"text","text":". You "},{"type":"strong","inlineContent":[{"type":"text","text":"must"}]},{"type":"text","text":" assign it before using IDCheckProcessAPI. We provide a default theme that you can use like this: "},{"type":"codeVoice","code":"IDCheckProcessAPI.theme = IDCheckTheme.default"},{"type":"text","text":". The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib"},{"type":"text","text":" uses the theme to provide the translations for the new liveness component, to understand how you can create your custom theme please check "},{"type":"reference","isActive":true,"identifier":"https:\/\/lawicko.github.io\/idcheckuilib\/2.1.0\/tutorials\/idcheckuilib\/theming"},{"type":"text","text":"."}]}]}]},{"anchor":"Future-versions","level":2,"type":"heading","text":"Future versions"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Version 6.1.0 was the last one that explain the migration in this form, if you need to migrate past 6.1.0 onto the later versions, please refer to out tutorials section: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/tutorials\/Tutorial-Table-of-Contents"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idchecklib\/migration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idchecklib\/migration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/Migration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"How to adapt your code when updating the library to the latest version"}],"kind":"article","metadata":{"roleHeading":"Article","title":"Migration from previous versions","role":"article","modules":[{"name":"IDCheckLib"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib"]]},"references":{"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationAPI":{"role":"symbol","title":"IDCheckSelfieVerificationAPI","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationAPI"}],"abstract":[{"type":"text","text":"This API groups all the tasks for the selfie verification"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationAPI"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationapi"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckProcessAPI/addressVerificationAPI":{"role":"symbol","title":"addressVerificationAPI","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressVerificationAPI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckAddressVerificationAPI","preciseIdentifier":"s:10IDCheckLib0A22AddressVerificationAPIV"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI\/addressVerificationAPI","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckprocessapi\/addressverificationapi"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckProcessAPI/documentCorrectionAPI":{"role":"symbol","title":"documentCorrectionAPI","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentCorrectionAPI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckDocumentCorrectionAPI","preciseIdentifier":"s:10IDCheckLib0A21DocumentCorrectionAPIV"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI\/documentCorrectionAPI","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckprocessapi\/documentcorrectionapi"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckProcessAPI/init(config:processID:certificatesInfo:)":{"role":"symbol","title":"init(config:processID:certificatesInfo:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckConfig","preciseIdentifier":"s:10IDCheckLib0A6ConfigV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"processID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"certificatesInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CertificatesInfo","preciseIdentifier":"s:10NetworkSDK16CertificatesInfoV"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Use this to initialize your instance of the "},{"type":"codeVoice","code":"IDCheckProcessAPI"},{"type":"text","text":"."}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI\/init(config:processID:certificatesInfo:)","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckprocessapi\/init(config:processid:certificatesinfo:)"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckTaskLivenessVerify":{"role":"symbol","title":"IDCheckTaskLivenessVerify","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckTaskLivenessVerify"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskLivenessVerify","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckTaskLivenessVerify"}],"url":"\/documentation\/idchecklib\/idchecktasklivenessverify"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckScanMode":{"role":"symbol","title":"IDCheckScanMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckScanMode"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckScanMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckScanMode"}],"url":"\/documentation\/idchecklib\/idcheckscanmode"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckTaskLivenessVerify/images":{"role":"symbol","title":"images","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"images"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskLivenessVerify\/images","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idchecktasklivenessverify\/images"},"https://lawicko.github.io/idcheckuilib/2.1.0/tutorials/idcheckuilib/theming":{"title":"this tutorial","titleInlineContent":[{"type":"text","text":"this tutorial"}],"type":"link","identifier":"https:\/\/lawicko.github.io\/idcheckuilib\/2.1.0\/tutorials\/idcheckuilib\/theming","url":"https:\/\/lawicko.github.io\/idcheckuilib\/2.1.0\/tutorials\/idcheckuilib\/theming"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationViewControllerDelegate":{"role":"symbol","title":"IDCheckSelfieVerificationViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationViewControllerDelegate"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckRecognizedArea":{"role":"symbol","title":"IDCheckRecognizedArea","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckRecognizedArea"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedArea","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckRecognizedArea"}],"url":"\/documentation\/idchecklib\/idcheckrecognizedarea"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckLoggerProtocol/warn(_:)":{"role":"symbol","title":"warn(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"warn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckLoggerProtocol\/warn(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/idchecklib\/idcheckloggerprotocol\/warn(_:)"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckTaskState/aborted":{"role":"symbol","title":"IDCheckTaskState.aborted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"aborted"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskState\/aborted","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idchecktaskstate\/aborted"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationCameraSettings":{"role":"symbol","title":"IDCheckSelfieVerificationCameraSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationCameraSettings"}],"abstract":[{"type":"text","text":"SelfieCameraSettings"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationCameraSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationCameraSettings"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationcamerasettings"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationViewController":{"role":"symbol","title":"IDCheckSelfieVerificationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationViewController"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationviewcontroller"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationPage":{"role":"symbol","title":"IDCheckDocumentVerificationPage","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentVerificationPage"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationPage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentVerificationPage"}],"url":"\/documentation\/idchecklib\/idcheckdocumentverificationpage"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationViewController":{"role":"symbol","title":"IDCheckDocumentVerificationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentVerificationViewController"}],"abstract":[{"type":"text","text":"This view controller verifies the documents, it communicates with the integrating application through it’s delegate protocol"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentVerificationViewController"}],"url":"\/documentation\/idchecklib\/idcheckdocumentverificationviewcontroller"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationViewControllerDelegate":{"role":"symbol","title":"IDCheckDocumentVerificationViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentVerificationViewControllerDelegate"}],"abstract":[{"type":"text","text":"This protocol is used for communication between the IDCheckDocumentVerificationViewController and it’s delegate"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentVerificationViewControllerDelegate"}],"url":"\/documentation\/idchecklib\/idcheckdocumentverificationviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckProcessAPI/selfieVerificationAPI":{"role":"symbol","title":"selfieVerificationAPI","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"selfieVerificationAPI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckSelfieVerificationAPI","preciseIdentifier":"s:10IDCheckLib0A21SelfieVerificationAPIV"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI\/selfieVerificationAPI","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckprocessapi\/selfieverificationapi"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationViewControllerDelegate/documentVerificationRequire(_:lastScan:)-6xviq":{"role":"symbol","title":"documentVerificationRequire(_:lastScan:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentVerificationRequire"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckDocumentVerificationPage","preciseIdentifier":"s:10IDCheckLib0A24DocumentVerificationPageO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lastScan"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckDocumentVerificationPage","preciseIdentifier":"s:10IDCheckLib0A24DocumentVerificationPageO"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewControllerDelegate\/documentVerificationRequire(_:lastScan:)-6xviq","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckdocumentverificationviewcontrollerdelegate\/documentverificationrequire(_:lastscan:)-6xviq"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckAddressVerificationAPI":{"role":"symbol","title":"IDCheckAddressVerificationAPI","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckAddressVerificationAPI"}],"abstract":[{"type":"text","text":"This API groups all the tasks for the address verification"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckAddressVerificationAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckAddressVerificationAPI"}],"url":"\/documentation\/idchecklib\/idcheckaddressverificationapi"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckLoggerProtocol":{"role":"symbol","title":"IDCheckLoggerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckLoggerProtocol"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckLoggerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckLoggerProtocol"}],"url":"\/documentation\/idchecklib\/idcheckloggerprotocol"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib":{"role":"collection","title":"IDCheckLib","abstract":[{"type":"text","text":"IDCheckLib - document verification"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckProcessAPI":{"role":"symbol","title":"IDCheckProcessAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckProcessAPI"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckProcessAPI"}],"url":"\/documentation\/idchecklib\/idcheckprocessapi"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckProcessAPI/abort(taskID:completionHandler:)":{"role":"symbol","title":"abort(taskID:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"abort"},{"kind":"text","text":"("},{"kind":"externalParam","text":"taskID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Aborts the task with the specified ID"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI\/abort(taskID:completionHandler:)","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckprocessapi\/abort(taskid:completionhandler:)"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/Version":{"role":"article","title":"6.1.1","abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/Version","kind":"article","type":"topic","url":"\/documentation\/idchecklib\/version"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDVerificationAPI":{"role":"symbol","title":"IDCheckEMRTDVerificationAPI","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckEMRTDVerificationAPI"}],"abstract":[{"type":"text","text":"This API groups all the tasks for the EMRTD verification"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDVerificationAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckEMRTDVerificationAPI"}],"url":"\/documentation\/idchecklib\/idcheckemrtdverificationapi"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationViewControllerInsufficiencyDelegate":{"role":"symbol","title":"IDCheckDocumentVerificationViewControllerInsufficiencyDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentVerificationViewControllerInsufficiencyDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewControllerInsufficiencyDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentVerificationViewControllerInsufficiencyDelegate"}],"url":"\/documentation\/idchecklib\/idcheckdocumentverificationviewcontrollerinsufficiencydelegate"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckTaskDocumentVerify":{"role":"symbol","title":"IDCheckTaskDocumentVerify","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckTaskDocumentVerify"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskDocumentVerify","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckTaskDocumentVerify"}],"url":"\/documentation\/idchecklib\/idchecktaskdocumentverify"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckConfig":{"role":"symbol","title":"IDCheckConfig","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckConfig"}],"abstract":[{"type":"text","text":"This struct is used to carry all the critical configuration information for your IDCheckLib integration"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckConfig"}],"url":"\/documentation\/idchecklib\/idcheckconfig"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationAPI":{"role":"symbol","title":"IDCheckDocumentVerificationAPI","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentVerificationAPI"}],"abstract":[{"type":"text","text":"This API groups all the tasks for the document verification"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentVerificationAPI"}],"url":"\/documentation\/idchecklib\/idcheckdocumentverificationapi"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckProcessAPI/documentVerificationAPI":{"role":"symbol","title":"documentVerificationAPI","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentVerificationAPI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckDocumentVerificationAPI","preciseIdentifier":"s:10IDCheckLib0A23DocumentVerificationAPIV"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI\/documentVerificationAPI","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckprocessapi\/documentverificationapi"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckProcessAPI/emrtdVerificationAPI":{"role":"symbol","title":"emrtdVerificationAPI","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"emrtdVerificationAPI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckEMRTDVerificationAPI","preciseIdentifier":"s:10IDCheckLib0A20EMRTDVerificationAPIV"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI\/emrtdVerificationAPI","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckprocessapi\/emrtdverificationapi"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationViewControllerDelegate/documentVerificationRequire(_:)-9i4fd":{"role":"symbol","title":"documentVerificationRequire(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentVerificationRequire"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckDocumentVerificationPage","preciseIdentifier":"s:10IDCheckLib0A24DocumentVerificationPageO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewControllerDelegate\/documentVerificationRequire(_:)-9i4fd","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckdocumentverificationviewcontrollerdelegate\/documentverificationrequire(_:)-9i4fd"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentCorrectionAPI":{"role":"symbol","title":"IDCheckDocumentCorrectionAPI","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentCorrectionAPI"}],"abstract":[{"type":"text","text":"This API groups all the tasks for the document correction"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentCorrectionAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentCorrectionAPI"}],"url":"\/documentation\/idchecklib\/idcheckdocumentcorrectionapi"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationLegacyViewControllerDelegate":{"role":"symbol","title":"IDCheckSelfieVerificationLegacyViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewControllerDelegate"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.library/tutorials/Tutorial-Table-of-Contents":{"role":"overview","title":"Introducing IDCheckLib","abstract":[{"type":"text","text":"IDCheckLib is a module for integrating the ti&m IDCheck functionality into your iOS application."}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/tutorials\/Tutorial-Table-of-Contents","kind":"overview","type":"topic","url":"\/tutorials\/tutorial-table-of-contents"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationLegacyViewController":{"role":"symbol","title":"IDCheckSelfieVerificationLegacyViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"}],"abstract":[{"type":"text","text":"This view controller verifies the selfies, it communicates with the integrating application through it’s delegate protocol"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckTaskLivenessVerify/requiredHeadPoses":{"role":"symbol","title":"requiredHeadPoses","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredHeadPoses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"IDCheckHeadPose","preciseIdentifier":"s:10IDCheckLib0A8HeadPoseO"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskLivenessVerify\/requiredHeadPoses","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idchecktasklivenessverify\/requiredheadposes"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckNextTask/taskPreviousInformation":{"role":"symbol","title":"taskPreviousInformation","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"taskPreviousInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckTaskPreviousInformation","preciseIdentifier":"s:10IDCheckLib0A23TaskPreviousInformationV"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckNextTask\/taskPreviousInformation","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idchecknexttask\/taskpreviousinformation"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckProcessAPI/theme":{"role":"symbol","title":"theme","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"theme"},{"kind":"text","text":": IDCheckUITheme"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"IDCheckStyle","preciseIdentifier":"s:14IDCheckUITheme0A5StyleP"}],"abstract":[{"type":"text","text":"This defines, which assets are used by IDCheckLib. As of version 6.0 this is mainly for the liveness styling, however it is possible that the usage of this property may be exteneded to other modules in the future versions."}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI\/theme","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckprocessapi\/theme"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckTaskDocumentVerify/images":{"role":"symbol","title":"images","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"images"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]]?"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskDocumentVerify\/images","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idchecktaskdocumentverify\/images"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationViewController\/title","value":"IDCheckSelfieVerificationViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckSelfieVerificationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckDocumentVerificationViewController\/title","value":"IDCheckDocumentVerificationViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckDocumentVerificationViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckDocumentVerificationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationLegacyViewController\/title","value":"IDCheckSelfieVerificationLegacyViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationLegacyViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}