{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckRecognizedAreasView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idchecklib\/idcheckrecognizedareasview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idchecklib\/idcheckrecognizedareasview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.library\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSCoding","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSObject","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)CALayerDelegate","doc:\/\/ch.ti8m.idcheck.library\/s7CVarArgP","doc:\/\/ch.ti8m.idcheck.library\/s28CustomDebugStringConvertibleP","doc:\/\/ch.ti8m.idcheck.library\/s23CustomStringConvertibleP","doc:\/\/ch.ti8m.idcheck.library\/SQ","doc:\/\/ch.ti8m.idcheck.library\/SH","doc:\/\/ch.ti8m.idcheck.library\/s8SendableP","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIAccessibilityIdentification","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIAppearance","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIAppearanceContainer","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UICoordinateSpace","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIDynamicItem","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIFocusEnvironment","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIFocusItem","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIFocusItemContainer","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UILargeContentViewerItem","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIResponderStandardEditActions","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UITraitEnvironment","doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedAreasView","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedAreasView\/lineColor","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedAreasView\/recognizedAreas","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedAreasView\/resolution"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckRecognizedAreasView"}],"title":"IDCheckRecognizedAreasView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@IDCheckLib@objc(cs)IDCheckRecognizedAreasView","modules":[{"name":"IDCheckLib"}],"navigatorTitle":[{"kind":"identifier","text":"IDCheckRecognizedAreasView"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib"]]},"references":{"doc://ch.ti8m.idcheck.library/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSObject"},"doc://ch.ti8m.idcheck.library/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)CALayerDelegate"},"doc://ch.ti8m.idcheck.library/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIUserActivityRestoring"},"doc://ch.ti8m.idcheck.library/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIAppearanceContainer"},"doc://ch.ti8m.idcheck.library/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/ch.ti8m.idcheck.library\/s8SendableP"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckRecognizedAreasView/lineColor":{"role":"symbol","title":"lineColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedAreasView\/lineColor","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckrecognizedareasview\/linecolor"},"doc://ch.ti8m.idcheck.library/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://ch.ti8m.idcheck.library/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UITraitEnvironment"},"doc://ch.ti8m.idcheck.library/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ch.ti8m.idcheck.library\/SQ"},"doc://ch.ti8m.idcheck.library/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIResponderStandardEditActions"},"doc://ch.ti8m.idcheck.library/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UICoordinateSpace"},"doc://ch.ti8m.idcheck.library/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIDynamicItem"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib":{"role":"collection","title":"IDCheckLib","abstract":[{"type":"text","text":"IDCheckLib - document verification"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib"},"doc://ch.ti8m.idcheck.library/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIFocusEnvironment"},"doc://ch.ti8m.idcheck.library/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIAppearance"},"doc://ch.ti8m.idcheck.library/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIAccessibilityIdentification"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckRecognizedAreasView/resolution":{"role":"symbol","title":"resolution","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckResolution","preciseIdentifier":"s:10IDCheckLib0A10ResolutionO"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedAreasView\/resolution","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckrecognizedareasview\/resolution"},"doc://ch.ti8m.idcheck.library/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.library\/s28CustomDebugStringConvertibleP"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckRecognizedAreasView/recognizedAreas":{"role":"symbol","title":"recognizedAreas","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognizedAreas"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"IDCheckRecognizedArea","preciseIdentifier":"s:10IDCheckLib0A14RecognizedAreaV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedAreasView\/recognizedAreas","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckrecognizedareasview\/recognizedareas"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckRecognizedAreasView/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedAreasView\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/idchecklib\/idcheckrecognizedareasview\/initwithcoder:"},"doc://ch.ti8m.idcheck.library/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)NSCoding"},"doc://ch.ti8m.idcheck.library/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIFocusItem"},"doc://ch.ti8m.idcheck.library/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ch.ti8m.idcheck.library\/SH"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckRecognizedAreasView":{"role":"symbol","title":"IDCheckRecognizedAreasView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckRecognizedAreasView"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedAreasView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckRecognizedAreasView"}],"url":"\/documentation\/idchecklib\/idcheckrecognizedareasview"},"doc://ch.ti8m.idcheck.library/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/ch.ti8m.idcheck.library\/s7CVarArgP"},"doc://ch.ti8m.idcheck.library/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(cs)UIView"},"doc://ch.ti8m.idcheck.library/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIFocusItemContainer"},"doc://ch.ti8m.idcheck.library/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIPasteConfigurationSupporting"},"doc://ch.ti8m.idcheck.library/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckRecognizedAreasView/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedAreasView\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/idchecklib\/idcheckrecognizedareasview\/initwithframe:"},"doc://ch.ti8m.idcheck.library/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/ch.ti8m.idcheck.library\/objc(pl)UILargeContentViewerItem"},"doc://ch.ti8m.idcheck.library/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.library\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"IDCheckRecognizedAreasView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IDCheckRecognizedAreasView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IDCheckRecognizedAreasView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedAreasView\/initWithCoder:","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedAreasView\/initWithFrame:"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.library\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckRecognizedAreasView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckRecognizedAreasView\/title","value":"IDCheckRecognizedAreasView"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckRecognizedAreasView\/fragments","value":[{"kind":"identifier","text":"IDCheckRecognizedAreasView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}