{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller\/init(coder:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller\/init(coder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/init(coder:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"title":"init(coder:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@IDCheckLib@objc(cs)IDCheckSelfieVerificationLegacyViewController(im)initWithCoder:","modules":[{"name":"IDCheckLib"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController"]]},"references":{"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationLegacyViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller\/init(coder:)"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib":{"role":"collection","title":"IDCheckLib","abstract":[{"type":"text","text":"IDCheckLib - document verification"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationLegacyViewController":{"role":"symbol","title":"IDCheckSelfieVerificationLegacyViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"}],"abstract":[{"type":"text","text":"This view controller verifies the selfies, it communicates with the integrating application through it’s delegate protocol"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCoder:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"coder"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationLegacyViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationLegacyViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationLegacyViewController\/title","value":"IDCheckSelfieVerificationLegacyViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationLegacyViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}