{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idchecklib\/idcheckdocumentverificationviewcontroller\/viewdidload()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idchecklib\/idcheckdocumentverificationviewcontroller\/viewdidload()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewController\/viewDidLoad()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"title":"viewDidLoad()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@IDCheckLib@objc(cs)IDCheckDocumentVerificationViewController(im)viewDidLoad","modules":[{"name":"IDCheckLib"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewController"]]},"references":{"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/idchecklib\/idcheckdocumentverificationviewcontroller\/viewdidload()"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationViewController":{"role":"symbol","title":"IDCheckDocumentVerificationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentVerificationViewController"}],"abstract":[{"type":"text","text":"This view controller verifies the documents, it communicates with the integrating application through it’s delegate protocol"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentVerificationViewController"}],"url":"\/documentation\/idchecklib\/idcheckdocumentverificationviewcontroller"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib":{"role":"collection","title":"IDCheckLib","abstract":[{"type":"text","text":"IDCheckLib - document verification"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"viewDidLoad"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckDocumentVerificationViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckDocumentVerificationViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckDocumentVerificationViewController\/title","value":"IDCheckDocumentVerificationViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckDocumentVerificationViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckDocumentVerificationViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}