{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckConfig"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"Migration-from-previous-versions","level":2,"type":"heading","text":"Migration from previous versions"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is how the initialization of the "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"IDCheckConfig"}]}]},{"type":"text","text":" may have looked in version 3.5.x"}]},{"type":"codeListing","syntax":"swift","code":["\/\/ 3.5.x version","let cfg = IDCheckConfig(url: url,","                        socketUrl: socketUrl,","                        socketScanVersion: “v2”,","                        socketNfcVersion: “v1”,","                        tenantId: tenant,","                        versionIdCheckApi: “v5”,","                        customHeader: [:],","                        socketScanRelease:\"albis\",","                        certificates: certs,","                        pollingInterval: 5000)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here are the changes in the initializer signature for version 3.6.0:"}]},{"type":"codeListing","syntax":"swift","code":["\/\/ 3.6.0","let cfg = IDCheckConfig(apiURL: url, \/\/ parameter renamed from url to apiURL","                        socketScanURL: socketUrl, \/\/ parameter renamed from socketUrl to socketScanURL","                        socketEMRTDURL: socketUrl, \/\/ NEW","                        socketRelease: \"albis\",","                        loggingURL: \"\", \/\/ NEW","                        tenantID: tenant,","                        pollingInterval: 5000,","                        certificates: certs,","                        customHeaders: [:])"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"socketScanURL"}]}]},{"type":"text","text":" is used for document verification, so in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewController"},{"type":"text","text":". For example, this is how we define it in our sample app:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"wss:\/\/id-check-int.ti8m.ch\/delegate\/id-check-scan\/v2"}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"socketEMRTDURL"}]}]},{"type":"text","text":" is used by the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader"},{"type":"text","text":". For example, this is how we define it in our sample app:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"wss:\/\/id-check-int.ti8m.ch\/delegate\/id-check-emrtd\/v1"}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"loggingURL"}]}]},{"type":"text","text":" can be ignored (just pass an empty string)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The version parameters "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"socketScanVersion"}]}]},{"type":"text","text":", "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"socketNfcVersion"}]}]},{"type":"text","text":", "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"versionIdCheckApi"}]}]},{"type":"text","text":" are no longer there as we switched to specifying the version directly in the url (as you can see with the "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"socketScanURL"}]}]},{"type":"text","text":" and "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"socketEMRTDURL"}]}]},{"type":"text","text":"). Also the "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"socketScanURL"}]}]},{"type":"text","text":" now contains the version, like this (from our sample app):"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"https:\/\/id-check-int.ti8m.ch\/delegate\/id-check-process-adapter\/v5"}]}]}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idchecklib\/idcheckconfig"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This struct is used to carry all the critical configuration information for your IDCheckLib integration"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckConfig"}],"title":"IDCheckConfig","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"s:10IDCheckLib0A6ConfigV","modules":[{"name":"IDCheckLib"}],"navigatorTitle":[{"kind":"identifier","text":"IDCheckConfig"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/init(apiURL:socketScanURL:socketEMRTDURL:socketLivenessURL:loggingURL:tenantID:pollingInterval:certificates:customHeaders:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/apiURL","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/certificates","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/customHeaders","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/loggingURL","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/pollingInterval","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/socketEMRTDURL","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/socketLivenessURL","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/socketScanURL","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/tenantID"]}],"references":{"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationViewController":{"role":"symbol","title":"IDCheckDocumentVerificationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentVerificationViewController"}],"abstract":[{"type":"text","text":"This view controller verifies the documents, it communicates with the integrating application through it’s delegate protocol"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentVerificationViewController"}],"url":"\/documentation\/idchecklib\/idcheckdocumentverificationviewcontroller"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckConfig/loggingURL":{"role":"symbol","title":"loggingURL","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"loggingURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/loggingURL","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckconfig\/loggingurl"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckConfig":{"role":"symbol","title":"IDCheckConfig","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckConfig"}],"abstract":[{"type":"text","text":"This struct is used to carry all the critical configuration information for your IDCheckLib integration"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckConfig"}],"url":"\/documentation\/idchecklib\/idcheckconfig"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckConfig/customHeaders":{"role":"symbol","title":"customHeaders","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"customHeaders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/customHeaders","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckconfig\/customheaders"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckConfig/socketScanURL":{"role":"symbol","title":"socketScanURL","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"socketScanURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/socketScanURL","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckconfig\/socketscanurl"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckConfig/certificates":{"role":"symbol","title":"certificates","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"certificates"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/certificates","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckconfig\/certificates"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckConfig/init(apiURL:socketScanURL:socketEMRTDURL:socketLivenessURL:loggingURL:tenantID:pollingInterval:certificates:customHeaders:)":{"role":"symbol","title":"init(apiURL:socketScanURL:socketEMRTDURL:socketLivenessURL:loggingURL:tenantID:pollingInterval:certificates:customHeaders:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"apiURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socketScanURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socketEMRTDURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socketLivenessURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loggingURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tenantID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pollingInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"certificates"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"customHeaders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Creates an instance configured with all required parameters"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/init(apiURL:socketScanURL:socketEMRTDURL:socketLivenessURL:loggingURL:tenantID:pollingInterval:certificates:customHeaders:)","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckconfig\/init(apiurl:socketscanurl:socketemrtdurl:socketlivenessurl:loggingurl:tenantid:pollinginterval:certificates:customheaders:)"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckConfig/tenantID":{"role":"symbol","title":"tenantID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"tenantID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/tenantID","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckconfig\/tenantid"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib":{"role":"collection","title":"IDCheckLib","abstract":[{"type":"text","text":"IDCheckLib - document verification"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDReader":{"role":"symbol","title":"IDCheckEMRTDReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckEMRTDReader"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckEMRTDReader"}],"url":"\/documentation\/idchecklib\/idcheckemrtdreader"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckConfig/socketEMRTDURL":{"role":"symbol","title":"socketEMRTDURL","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"socketEMRTDURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/socketEMRTDURL","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckconfig\/socketemrtdurl"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckConfig/socketLivenessURL":{"role":"symbol","title":"socketLivenessURL","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"socketLivenessURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/socketLivenessURL","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckconfig\/socketlivenessurl"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckConfig/pollingInterval":{"role":"symbol","title":"pollingInterval","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pollingInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/pollingInterval","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckconfig\/pollinginterval"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckConfig/apiURL":{"role":"symbol","title":"apiURL","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig\/apiURL","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idcheckconfig\/apiurl"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckDocumentVerificationViewController\/title","value":"IDCheckDocumentVerificationViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckDocumentVerificationViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckDocumentVerificationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckEMRTDReader\/title","value":"IDCheckEMRTDReader"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckEMRTDReader\/fragments","value":[{"kind":"identifier","text":"IDCheckEMRTDReader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}