{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Current-version","level":3,"type":"heading","text":"Current version"},{"type":"paragraph","inlineContent":[{"type":"text","text":"5.0.0"}]},{"anchor":"Requirements","level":3,"type":"heading","text":"Requirements"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Minimum iOS version is: 13, the iOS sdk used for compiling is 16.0 (Xcode 14.0)"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idchecklib"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idchecklib"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"IDCheckLib - document verification"}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"IDCheckLib","title":"IDCheckLib","symbolKind":"module","role":"collection","modules":[{"name":"IDCheckLib"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Articles","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/Components","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/Integration","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/Migration"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckCameraSettings","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationCameraSettings","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewController","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckLogger","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedAreasView","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationCameraSettings","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController"]},{"title":"Protocols","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckAbstractNamedConclusion","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckAbstractResult","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckAbstractTask","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckCompoundResult","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewControllerInsufficiencyDelegate","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReaderDelegate","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckLoggerProtocol","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/MessageProtocol"]},{"title":"Structures","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckActiveAuthentication","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckAddress","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckAddressResult","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckAddressResultNamedConclusion","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckAddressVerificationAPI","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckBiometricResult","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckBiometricResultNamedConclusion","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfigRead","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDataCrossCheckCombination","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDataCrossCheckCompoundResult","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDataCrossCheckNamedConclusion","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDataCrossCheckResult","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDataGroup","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDefaultCameraSettings","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentCorrection","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentCorrectionAPI","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentCrossCheckCombination","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentCrossCheckNamedConclusion","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentCrossCheckResult","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentReference","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentResult","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentResultNamedConclusion","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationAPI","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentsCompoundResult","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentsCrossCheckCompoundResult","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDDataElements","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDDocumentData","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDVerificationAPI","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckError","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckFlowDefinition","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckGenericTask","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckMRZ","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckNamedConclusion","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckNextTask","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckPreferredDocument","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessInformation","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessRead","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedArea","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckResult","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationAPI","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskAddressVerify","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskDataCrossCheck","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskDocumentCorrection","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskDocumentCrossCheck","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskDocumentVerify","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskEMRTDVerify","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskLivenessVerify","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskPreviousInformation","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckUserData","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckVertex","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/LogEntry","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/LoggingSystem","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/Step","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/TechnicalLogMessage","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/UserLogMessage"]},{"title":"Enumerations","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/CameraLogMessageAction","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/DefaultActions","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckChipAccessControlType","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConclusion","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentType","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationError","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationPage","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationResult","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDProtocol","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReaderError","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReaderStatus","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckHeadPose","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckLibNotificationUserInfoKey","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckModuleType","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckResolution","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckScanMode","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationError","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTask","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskState","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/LogLevel","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/UserLogMessageAction"]}],"references":{"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/UserLogMessage":{"role":"symbol","title":"UserLogMessage","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserLogMessage"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/UserLogMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserLogMessage"}],"url":"\/documentation\/idchecklib\/userlogmessage"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckNextTask":{"role":"symbol","title":"IDCheckNextTask","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckNextTask"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckNextTask","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckNextTask"}],"url":"\/documentation\/idchecklib\/idchecknexttask"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckVertex":{"role":"symbol","title":"IDCheckVertex","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckVertex"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckVertex","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckVertex"}],"url":"\/documentation\/idchecklib\/idcheckvertex"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDReader":{"role":"symbol","title":"IDCheckEMRTDReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckEMRTDReader"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckEMRTDReader"}],"url":"\/documentation\/idchecklib\/idcheckemrtdreader"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/LoggingSystem":{"role":"symbol","title":"LoggingSystem","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggingSystem"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/LoggingSystem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoggingSystem"}],"url":"\/documentation\/idchecklib\/loggingsystem"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDataCrossCheckNamedConclusion":{"role":"symbol","title":"IDCheckDataCrossCheckNamedConclusion","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDataCrossCheckNamedConclusion"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDataCrossCheckNamedConclusion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDataCrossCheckNamedConclusion"}],"url":"\/documentation\/idchecklib\/idcheckdatacrosschecknamedconclusion"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDataCrossCheckResult":{"role":"symbol","title":"IDCheckDataCrossCheckResult","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDataCrossCheckResult"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDataCrossCheckResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDataCrossCheckResult"}],"url":"\/documentation\/idchecklib\/idcheckdatacrosscheckresult"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/Components":{"role":"article","title":"Components","abstract":[{"type":"text","text":"The conceptual overview of the SDK"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/Components","kind":"article","type":"topic","url":"\/documentation\/idchecklib\/components"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDReaderStatus":{"role":"symbol","title":"IDCheckEMRTDReaderStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckEMRTDReaderStatus"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReaderStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckEMRTDReaderStatus"}],"url":"\/documentation\/idchecklib\/idcheckemrtdreaderstatus"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckAbstractNamedConclusion":{"role":"symbol","title":"IDCheckAbstractNamedConclusion","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckAbstractNamedConclusion"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckAbstractNamedConclusion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckAbstractNamedConclusion"}],"url":"\/documentation\/idchecklib\/idcheckabstractnamedconclusion"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentCrossCheckNamedConclusion":{"role":"symbol","title":"IDCheckDocumentCrossCheckNamedConclusion","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentCrossCheckNamedConclusion"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentCrossCheckNamedConclusion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentCrossCheckNamedConclusion"}],"url":"\/documentation\/idchecklib\/idcheckdocumentcrosschecknamedconclusion"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentsCompoundResult":{"role":"symbol","title":"IDCheckDocumentsCompoundResult","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentsCompoundResult"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentsCompoundResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentsCompoundResult"}],"url":"\/documentation\/idchecklib\/idcheckdocumentscompoundresult"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDDocumentData":{"role":"symbol","title":"IDCheckEMRTDDocumentData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckEMRTDDocumentData"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDDocumentData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckEMRTDDocumentData"}],"url":"\/documentation\/idchecklib\/idcheckemrtddocumentdata"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckResult":{"role":"symbol","title":"IDCheckResult","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckResult"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckResult"}],"url":"\/documentation\/idchecklib\/idcheckresult"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationAPI":{"role":"symbol","title":"IDCheckDocumentVerificationAPI","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentVerificationAPI"}],"abstract":[{"type":"text","text":"This API groups all the tasks for the document verification"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentVerificationAPI"}],"url":"\/documentation\/idchecklib\/idcheckdocumentverificationapi"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckTask":{"role":"symbol","title":"IDCheckTask","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckTask"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTask","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckTask"}],"url":"\/documentation\/idchecklib\/idchecktask"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckProcessRead":{"role":"symbol","title":"IDCheckProcessRead","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckProcessRead"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessRead","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckProcessRead"}],"url":"\/documentation\/idchecklib\/idcheckprocessread"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/LogEntry":{"role":"symbol","title":"LogEntry","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogEntry"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/LogEntry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogEntry"}],"url":"\/documentation\/idchecklib\/logentry"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/MessageProtocol":{"role":"symbol","title":"MessageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageProtocol"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/MessageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageProtocol"}],"url":"\/documentation\/idchecklib\/messageprotocol"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentResultNamedConclusion":{"role":"symbol","title":"IDCheckDocumentResultNamedConclusion","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentResultNamedConclusion"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentResultNamedConclusion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentResultNamedConclusion"}],"url":"\/documentation\/idchecklib\/idcheckdocumentresultnamedconclusion"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDDataElements":{"role":"symbol","title":"IDCheckEMRTDDataElements","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckEMRTDDataElements"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDDataElements","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckEMRTDDataElements"}],"url":"\/documentation\/idchecklib\/idcheckemrtddataelements"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/Integration":{"role":"article","title":"Integration","abstract":[{"type":"text","text":"Step by step guide how to integrate the IDCheckLib into your app."}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/Integration","kind":"article","type":"topic","url":"\/documentation\/idchecklib\/integration"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckTaskState":{"role":"symbol","title":"IDCheckTaskState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckTaskState"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckTaskState"}],"url":"\/documentation\/idchecklib\/idchecktaskstate"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationLegacyViewControllerDelegate":{"role":"symbol","title":"IDCheckSelfieVerificationLegacyViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewControllerDelegate"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckGenericTask":{"role":"symbol","title":"IDCheckGenericTask","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckGenericTask"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckGenericTask","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckGenericTask"}],"url":"\/documentation\/idchecklib\/idcheckgenerictask"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDReaderDelegate":{"role":"symbol","title":"IDCheckEMRTDReaderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckEMRTDReaderDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReaderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckEMRTDReaderDelegate"}],"url":"\/documentation\/idchecklib\/idcheckemrtdreaderdelegate"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationAPI":{"role":"symbol","title":"IDCheckSelfieVerificationAPI","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationAPI"}],"abstract":[{"type":"text","text":"This API groups all the tasks for the selfie verification"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationAPI"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationapi"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationLegacyViewController":{"role":"symbol","title":"IDCheckSelfieVerificationLegacyViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"}],"abstract":[{"type":"text","text":"This view controller verifies the selfies, it communicates with the integrating application through it’s delegate protocol"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationlegacyviewcontroller"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/Migration":{"role":"article","title":"Migration from previous versions","abstract":[{"type":"text","text":"How to adapt your code when updating the library to the latest version"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/Migration","kind":"article","type":"topic","url":"\/documentation\/idchecklib\/migration"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckTaskPreviousInformation":{"role":"symbol","title":"IDCheckTaskPreviousInformation","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckTaskPreviousInformation"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskPreviousInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckTaskPreviousInformation"}],"url":"\/documentation\/idchecklib\/idchecktaskpreviousinformation"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationViewControllerDelegate":{"role":"symbol","title":"IDCheckDocumentVerificationViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentVerificationViewControllerDelegate"}],"abstract":[{"type":"text","text":"This protocol is used for communication between the IDCheckDocumentVerificationViewController and it’s delegate"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentVerificationViewControllerDelegate"}],"url":"\/documentation\/idchecklib\/idcheckdocumentverificationviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckBiometricResult":{"role":"symbol","title":"IDCheckBiometricResult","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckBiometricResult"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckBiometricResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckBiometricResult"}],"url":"\/documentation\/idchecklib\/idcheckbiometricresult"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/UserLogMessageAction":{"role":"symbol","title":"UserLogMessageAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserLogMessageAction"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/UserLogMessageAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserLogMessageAction"}],"url":"\/documentation\/idchecklib\/userlogmessageaction"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationViewControllerInsufficiencyDelegate":{"role":"symbol","title":"IDCheckDocumentVerificationViewControllerInsufficiencyDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentVerificationViewControllerInsufficiencyDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewControllerInsufficiencyDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentVerificationViewControllerInsufficiencyDelegate"}],"url":"\/documentation\/idchecklib\/idcheckdocumentverificationviewcontrollerinsufficiencydelegate"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckLibVersionNumber":{"role":"symbol","title":"IDCheckLibVersionNumber","fragments":[{"kind":"identifier","text":"IDCheckLibVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for IDCheckLib."}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckLibVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idchecklibversionnumber"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/CameraLogMessageAction":{"role":"symbol","title":"CameraLogMessageAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraLogMessageAction"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/CameraLogMessageAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraLogMessageAction"}],"url":"\/documentation\/idchecklib\/cameralogmessageaction"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationError":{"role":"symbol","title":"IDCheckSelfieVerificationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationError"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationError"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationerror"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDReaderError":{"role":"symbol","title":"IDCheckEMRTDReaderError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckEMRTDReaderError"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReaderError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckEMRTDReaderError"}],"url":"\/documentation\/idchecklib\/idcheckemrtdreadererror"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentCrossCheckCombination":{"role":"symbol","title":"IDCheckDocumentCrossCheckCombination","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentCrossCheckCombination"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentCrossCheckCombination","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentCrossCheckCombination"}],"url":"\/documentation\/idchecklib\/idcheckdocumentcrosscheckcombination"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckCameraSettings":{"role":"symbol","title":"IDCheckCameraSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckCameraSettings"}],"abstract":[{"type":"text","text":"CameraSettings"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckCameraSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckCameraSettings"}],"url":"\/documentation\/idchecklib\/idcheckcamerasettings"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentsCrossCheckCompoundResult":{"role":"symbol","title":"IDCheckDocumentsCrossCheckCompoundResult","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentsCrossCheckCompoundResult"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentsCrossCheckCompoundResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentsCrossCheckCompoundResult"}],"url":"\/documentation\/idchecklib\/idcheckdocumentscrosscheckcompoundresult"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckConfigRead":{"role":"symbol","title":"IDCheckConfigRead","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckConfigRead"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfigRead","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckConfigRead"}],"url":"\/documentation\/idchecklib\/idcheckconfigread"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckPreferredDocument":{"role":"symbol","title":"IDCheckPreferredDocument","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckPreferredDocument"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckPreferredDocument","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckPreferredDocument"}],"url":"\/documentation\/idchecklib\/idcheckpreferreddocument"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckRecognizedAreasView":{"role":"symbol","title":"IDCheckRecognizedAreasView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckRecognizedAreasView"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedAreasView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckRecognizedAreasView"}],"url":"\/documentation\/idchecklib\/idcheckrecognizedareasview"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentCrossCheckResult":{"role":"symbol","title":"IDCheckDocumentCrossCheckResult","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentCrossCheckResult"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentCrossCheckResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentCrossCheckResult"}],"url":"\/documentation\/idchecklib\/idcheckdocumentcrosscheckresult"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckTaskDocumentCorrection":{"role":"symbol","title":"IDCheckTaskDocumentCorrection","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckTaskDocumentCorrection"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskDocumentCorrection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckTaskDocumentCorrection"}],"url":"\/documentation\/idchecklib\/idchecktaskdocumentcorrection"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckTaskDocumentCrossCheck":{"role":"symbol","title":"IDCheckTaskDocumentCrossCheck","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckTaskDocumentCrossCheck"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskDocumentCrossCheck","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckTaskDocumentCrossCheck"}],"url":"\/documentation\/idchecklib\/idchecktaskdocumentcrosscheck"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckUserData":{"role":"symbol","title":"IDCheckUserData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUserData"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckUserData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUserData"}],"url":"\/documentation\/idchecklib\/idcheckuserdata"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckNamedConclusion":{"role":"symbol","title":"IDCheckNamedConclusion","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckNamedConclusion"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckNamedConclusion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckNamedConclusion"}],"url":"\/documentation\/idchecklib\/idchecknamedconclusion"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationPage":{"role":"symbol","title":"IDCheckDocumentVerificationPage","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentVerificationPage"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationPage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentVerificationPage"}],"url":"\/documentation\/idchecklib\/idcheckdocumentverificationpage"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckLogger":{"role":"symbol","title":"IDCheckLogger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckLogger"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckLogger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckLogger"}],"url":"\/documentation\/idchecklib\/idchecklogger"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationViewControllerDelegate":{"role":"symbol","title":"IDCheckSelfieVerificationViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationViewControllerDelegate"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckResolution":{"role":"symbol","title":"IDCheckResolution","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckResolution"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckResolution","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckResolution"}],"url":"\/documentation\/idchecklib\/idcheckresolution"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckScanMode":{"role":"symbol","title":"IDCheckScanMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckScanMode"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckScanMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckScanMode"}],"url":"\/documentation\/idchecklib\/idcheckscanmode"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckTaskDocumentVerify":{"role":"symbol","title":"IDCheckTaskDocumentVerify","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckTaskDocumentVerify"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskDocumentVerify","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckTaskDocumentVerify"}],"url":"\/documentation\/idchecklib\/idchecktaskdocumentverify"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentCorrection":{"role":"symbol","title":"IDCheckDocumentCorrection","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentCorrection"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentCorrection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentCorrection"}],"url":"\/documentation\/idchecklib\/idcheckdocumentcorrection"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckChipAccessControlType":{"role":"symbol","title":"IDCheckChipAccessControlType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckChipAccessControlType"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckChipAccessControlType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckChipAccessControlType"}],"url":"\/documentation\/idchecklib\/idcheckchipaccesscontroltype"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckProcessAPI":{"role":"symbol","title":"IDCheckProcessAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckProcessAPI"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckProcessAPI"}],"url":"\/documentation\/idchecklib\/idcheckprocessapi"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentReference":{"role":"symbol","title":"IDCheckDocumentReference","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentReference"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentReference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentReference"}],"url":"\/documentation\/idchecklib\/idcheckdocumentreference"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckBiometricResultNamedConclusion":{"role":"symbol","title":"IDCheckBiometricResultNamedConclusion","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckBiometricResultNamedConclusion"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckBiometricResultNamedConclusion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckBiometricResultNamedConclusion"}],"url":"\/documentation\/idchecklib\/idcheckbiometricresultnamedconclusion"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckFlowDefinition":{"role":"symbol","title":"IDCheckFlowDefinition","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckFlowDefinition"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckFlowDefinition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckFlowDefinition"}],"url":"\/documentation\/idchecklib\/idcheckflowdefinition"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckTaskLivenessVerify":{"role":"symbol","title":"IDCheckTaskLivenessVerify","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckTaskLivenessVerify"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskLivenessVerify","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckTaskLivenessVerify"}],"url":"\/documentation\/idchecklib\/idchecktasklivenessverify"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationError":{"role":"symbol","title":"IDCheckDocumentVerificationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentVerificationError"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentVerificationError"}],"url":"\/documentation\/idchecklib\/idcheckdocumentverificationerror"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckAbstractTask":{"role":"symbol","title":"IDCheckAbstractTask","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckAbstractTask"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckAbstractTask","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckAbstractTask"}],"url":"\/documentation\/idchecklib\/idcheckabstracttask"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckMRZ":{"role":"symbol","title":"IDCheckMRZ","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckMRZ"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckMRZ","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckMRZ"}],"url":"\/documentation\/idchecklib\/idcheckmrz"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationResult":{"role":"symbol","title":"IDCheckDocumentVerificationResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentVerificationResult"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentVerificationResult"}],"url":"\/documentation\/idchecklib\/idcheckdocumentverificationresult"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDefaultCameraSettings":{"role":"symbol","title":"IDCheckDefaultCameraSettings","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDefaultCameraSettings"}],"abstract":[{"type":"text","text":"DefaultCameraSettings"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDefaultCameraSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDefaultCameraSettings"}],"url":"\/documentation\/idchecklib\/idcheckdefaultcamerasettings"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckLoggerProtocol":{"role":"symbol","title":"IDCheckLoggerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckLoggerProtocol"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckLoggerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckLoggerProtocol"}],"url":"\/documentation\/idchecklib\/idcheckloggerprotocol"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckCompoundResult":{"role":"symbol","title":"IDCheckCompoundResult","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckCompoundResult"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckCompoundResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckCompoundResult"}],"url":"\/documentation\/idchecklib\/idcheckcompoundresult"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentResult":{"role":"symbol","title":"IDCheckDocumentResult","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentResult"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentResult"}],"url":"\/documentation\/idchecklib\/idcheckdocumentresult"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/TechnicalLogMessage":{"role":"symbol","title":"TechnicalLogMessage","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TechnicalLogMessage"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/TechnicalLogMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TechnicalLogMessage"}],"url":"\/documentation\/idchecklib\/technicallogmessage"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/DefaultActions":{"role":"symbol","title":"DefaultActions","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultActions"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/DefaultActions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultActions"}],"url":"\/documentation\/idchecklib\/defaultactions"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationViewController":{"role":"symbol","title":"IDCheckDocumentVerificationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentVerificationViewController"}],"abstract":[{"type":"text","text":"This view controller verifies the documents, it communicates with the integrating application through it’s delegate protocol"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentVerificationViewController"}],"url":"\/documentation\/idchecklib\/idcheckdocumentverificationviewcontroller"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckTaskDataCrossCheck":{"role":"symbol","title":"IDCheckTaskDataCrossCheck","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckTaskDataCrossCheck"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskDataCrossCheck","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckTaskDataCrossCheck"}],"url":"\/documentation\/idchecklib\/idchecktaskdatacrosscheck"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckAbstractResult":{"role":"symbol","title":"IDCheckAbstractResult","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckAbstractResult"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckAbstractResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckAbstractResult"}],"url":"\/documentation\/idchecklib\/idcheckabstractresult"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckAddressVerificationAPI":{"role":"symbol","title":"IDCheckAddressVerificationAPI","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckAddressVerificationAPI"}],"abstract":[{"type":"text","text":"This API groups all the tasks for the address verification"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckAddressVerificationAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckAddressVerificationAPI"}],"url":"\/documentation\/idchecklib\/idcheckaddressverificationapi"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDataCrossCheckCompoundResult":{"role":"symbol","title":"IDCheckDataCrossCheckCompoundResult","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDataCrossCheckCompoundResult"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDataCrossCheckCompoundResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDataCrossCheckCompoundResult"}],"url":"\/documentation\/idchecklib\/idcheckdatacrosscheckcompoundresult"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckConclusion":{"role":"symbol","title":"IDCheckConclusion","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckConclusion"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConclusion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckConclusion"}],"url":"\/documentation\/idchecklib\/idcheckconclusion"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDVerificationAPI":{"role":"symbol","title":"IDCheckEMRTDVerificationAPI","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckEMRTDVerificationAPI"}],"abstract":[{"type":"text","text":"This API groups all the tasks for the EMRTD verification"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDVerificationAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckEMRTDVerificationAPI"}],"url":"\/documentation\/idchecklib\/idcheckemrtdverificationapi"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckActiveAuthentication":{"role":"symbol","title":"IDCheckActiveAuthentication","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckActiveAuthentication"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckActiveAuthentication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckActiveAuthentication"}],"url":"\/documentation\/idchecklib\/idcheckactiveauthentication"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentCorrectionAPI":{"role":"symbol","title":"IDCheckDocumentCorrectionAPI","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentCorrectionAPI"}],"abstract":[{"type":"text","text":"This API groups all the tasks for the document correction"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentCorrectionAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentCorrectionAPI"}],"url":"\/documentation\/idchecklib\/idcheckdocumentcorrectionapi"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckHeadPose":{"role":"symbol","title":"IDCheckHeadPose","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckHeadPose"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckHeadPose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckHeadPose"}],"url":"\/documentation\/idchecklib\/idcheckheadpose"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDataCrossCheckCombination":{"role":"symbol","title":"IDCheckDataCrossCheckCombination","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDataCrossCheckCombination"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDataCrossCheckCombination","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDataCrossCheckCombination"}],"url":"\/documentation\/idchecklib\/idcheckdatacrosscheckcombination"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckAddress":{"role":"symbol","title":"IDCheckAddress","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckAddress"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckAddress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckAddress"}],"url":"\/documentation\/idchecklib\/idcheckaddress"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/Step":{"role":"symbol","title":"Step","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Step"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/Step","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Step"}],"url":"\/documentation\/idchecklib\/step"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckProcessInformation":{"role":"symbol","title":"IDCheckProcessInformation","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckProcessInformation"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckProcessInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckProcessInformation"}],"url":"\/documentation\/idchecklib\/idcheckprocessinformation"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentVerificationCameraSettings":{"role":"symbol","title":"IDCheckDocumentVerificationCameraSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentVerificationCameraSettings"}],"abstract":[{"type":"text","text":"DocumentCameraSettings"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationCameraSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentVerificationCameraSettings"}],"url":"\/documentation\/idchecklib\/idcheckdocumentverificationcamerasettings"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckRecognizedArea":{"role":"symbol","title":"IDCheckRecognizedArea","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckRecognizedArea"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedArea","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckRecognizedArea"}],"url":"\/documentation\/idchecklib\/idcheckrecognizedarea"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckModuleType":{"role":"symbol","title":"IDCheckModuleType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckModuleType"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckModuleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckModuleType"}],"url":"\/documentation\/idchecklib\/idcheckmoduletype"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckAddressResult":{"role":"symbol","title":"IDCheckAddressResult","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckAddressResult"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckAddressResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckAddressResult"}],"url":"\/documentation\/idchecklib\/idcheckaddressresult"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDataGroup":{"role":"symbol","title":"IDCheckDataGroup","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDataGroup"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDataGroup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDataGroup"}],"url":"\/documentation\/idchecklib\/idcheckdatagroup"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckAddressResultNamedConclusion":{"role":"symbol","title":"IDCheckAddressResultNamedConclusion","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckAddressResultNamedConclusion"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckAddressResultNamedConclusion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckAddressResultNamedConclusion"}],"url":"\/documentation\/idchecklib\/idcheckaddressresultnamedconclusion"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckConfig":{"role":"symbol","title":"IDCheckConfig","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckConfig"}],"abstract":[{"type":"text","text":"This struct is used to carry all the critical configuration information for your IDCheckLib integration"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckConfig"}],"url":"\/documentation\/idchecklib\/idcheckconfig"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckDocumentType":{"role":"symbol","title":"IDCheckDocumentType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckDocumentType"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckDocumentType"}],"url":"\/documentation\/idchecklib\/idcheckdocumenttype"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckEMRTDProtocol":{"role":"symbol","title":"IDCheckEMRTDProtocol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckEMRTDProtocol"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckEMRTDProtocol"}],"url":"\/documentation\/idchecklib\/idcheckemrtdprotocol"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationCameraSettings":{"role":"symbol","title":"IDCheckSelfieVerificationCameraSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationCameraSettings"}],"abstract":[{"type":"text","text":"SelfieCameraSettings"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationCameraSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationCameraSettings"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationcamerasettings"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/LogLevel":{"role":"symbol","title":"LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/LogLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"url":"\/documentation\/idchecklib\/loglevel"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckLibNotificationUserInfoKey":{"role":"symbol","title":"IDCheckLibNotificationUserInfoKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckLibNotificationUserInfoKey"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckLibNotificationUserInfoKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckLibNotificationUserInfoKey"}],"url":"\/documentation\/idchecklib\/idchecklibnotificationuserinfokey"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckError":{"role":"symbol","title":"IDCheckError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckError"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckError"}],"url":"\/documentation\/idchecklib\/idcheckerror"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckLibVersionString":{"role":"symbol","title":"IDCheckLibVersionString","fragments":[{"kind":"identifier","text":"IDCheckLibVersionString"}],"abstract":[{"type":"text","text":"Project version string for IDCheckLib."}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckLibVersionString","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib\/idchecklibversionstring"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckTaskAddressVerify":{"role":"symbol","title":"IDCheckTaskAddressVerify","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckTaskAddressVerify"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskAddressVerify","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckTaskAddressVerify"}],"url":"\/documentation\/idchecklib\/idchecktaskaddressverify"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckSelfieVerificationViewController":{"role":"symbol","title":"IDCheckSelfieVerificationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckSelfieVerificationViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckSelfieVerificationViewController"}],"url":"\/documentation\/idchecklib\/idcheckselfieverificationviewcontroller"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib/IDCheckTaskEMRTDVerify":{"role":"symbol","title":"IDCheckTaskEMRTDVerify","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckTaskEMRTDVerify"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckTaskEMRTDVerify","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckTaskEMRTDVerify"}],"url":"\/documentation\/idchecklib\/idchecktaskemrtdverify"},"doc://ch.ti8m.idcheck.library/documentation/IDCheckLib":{"role":"collection","title":"IDCheckLib","abstract":[{"type":"text","text":"IDCheckLib - document verification"}],"identifier":"doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib","kind":"symbol","type":"topic","url":"\/documentation\/idchecklib"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Articles","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/Components","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/Integration","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/Migration"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckDocumentVerificationViewController","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckEMRTDReader","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckRecognizedAreasView","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationLegacyViewController","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckSelfieVerificationViewController"]},{"title":"Variables","identifiers":["doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckLibVersionNumber","doc:\/\/ch.ti8m.idcheck.library\/documentation\/IDCheckLib\/IDCheckLibVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckEMRTDReader\/title","value":"IDCheckEMRTDReader"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckEMRTDReader\/fragments","value":[{"kind":"identifier","text":"IDCheckEMRTDReader"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationLegacyViewController\/title","value":"IDCheckSelfieVerificationLegacyViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationLegacyViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckSelfieVerificationLegacyViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckRecognizedAreasView\/title","value":"IDCheckRecognizedAreasView"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckRecognizedAreasView\/fragments","value":[{"kind":"identifier","text":"IDCheckRecognizedAreasView"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckDocumentVerificationViewController\/title","value":"IDCheckDocumentVerificationViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckDocumentVerificationViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckDocumentVerificationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationViewController\/title","value":"IDCheckSelfieVerificationViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.library~1documentation~1IDCheckLib~1IDCheckSelfieVerificationViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckSelfieVerificationViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}